//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialEmpleos
    {
        public Nullable<int> CódigoEmpleado { get; set; }
        public Nullable<int> CódigoEmpleo { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeFin { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Empleos Empleos { get; set; }
    }
}
