//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.CLIENTEXARTICULO = new HashSet<CLIENTEXARTICULO>();
        }
    
        public string codarticulo { get; set; }
        public string descripcion { get; set; }
        public string pais { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string tipo { get; set; }
        public string paraofrecer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTEXARTICULO> CLIENTEXARTICULO { get; set; }
    }
}
